package db

import (
	"context"
	"fmt"
	"log"

	"github.com/jackc/pgx/v5/pgxpool"
)

// ── tiny helpers to reduce noise in the data literals ──

type TopicDef struct {
	Name       string
	ExamTarget string // "JEE" | "NEET" | "BOTH"; "" inherits from chapter
}

type ChapterDef struct {
	Name       string
	ExamTarget string
	Topics     []TopicDef
}

type SubjectDef struct {
	Name     string
	Chapters []ChapterDef
}

// t returns a topic that inherits the chapter's exam_target.
func t(name string) TopicDef { return TopicDef{Name: name} }

// tj returns a JEE-only topic (Advanced-level content not in NEET).
func tj(name string) TopicDef { return TopicDef{Name: name, ExamTarget: "JEE"} }

// tn returns a NEET-only topic.
func tn(name string) TopicDef { return TopicDef{Name: name, ExamTarget: "NEET"} }

// Seed populates the subjects → chapters → topics taxonomy from
// the official JEE (Main+Advanced) and NEET syllabi.
// It is idempotent: skips if subjects table is already populated.
func Seed(pool *pgxpool.Pool) error {
	var count int
	if err := pool.QueryRow(context.Background(),
		"SELECT COUNT(*) FROM subjects",
	).Scan(&count); err != nil {
		return fmt.Errorf("seed: check existing: %w", err)
	}
	if count > 0 {
		log.Println("seed: taxonomy already populated, skipping")
		return nil
	}

	subjects := BuildTaxonomy()

	ctx := context.Background()
	tx, err := pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("seed: begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	total := 0
	for _, subj := range subjects {
		var subjectID int64
		err := tx.QueryRow(ctx,
			`INSERT INTO subjects (name) VALUES ($1)
			 ON CONFLICT (name) DO UPDATE SET name=EXCLUDED.name
			 RETURNING subject_id`,
			subj.Name,
		).Scan(&subjectID)
		if err != nil {
			return fmt.Errorf("seed: insert subject %q: %w", subj.Name, err)
		}

		for sortOrder, ch := range subj.Chapters {
			var chapterID int64
			err := tx.QueryRow(ctx,
				`INSERT INTO chapters (subject_id, name, exam_target, sort_order)
				 VALUES ($1, $2, $3, $4)
				 ON CONFLICT (subject_id, name)
				 DO UPDATE SET exam_target=EXCLUDED.exam_target, sort_order=EXCLUDED.sort_order
				 RETURNING chapter_id`,
				subjectID, ch.Name, ch.ExamTarget, sortOrder+1,
			).Scan(&chapterID)
			if err != nil {
				return fmt.Errorf("seed: insert chapter %q: %w", ch.Name, err)
			}

			for _, tp := range ch.Topics {
				target := tp.ExamTarget
				if target == "" {
					target = ch.ExamTarget
				}
				if _, err := tx.Exec(ctx,
					`INSERT INTO topics (chapter_id, name, exam_target)
					 VALUES ($1, $2, $3)
					 ON CONFLICT (chapter_id, name) DO NOTHING`,
					chapterID, tp.Name, target,
				); err != nil {
					return fmt.Errorf("seed: insert topic %q: %w", tp.Name, err)
				}
				total++
			}
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("seed: commit: %w", err)
	}
	log.Printf("seed: inserted %d topics across %d subjects", total, len(subjects))
	return nil
}

// ─────────────────────────────────────────────────────────────────
//  TAXONOMY DATA — sourced from:
//   • JEE (Main) 2026 Syllabus
//   • JEE (Advanced) 2026 Syllabus
//   • NEET (UG) 2026 Syllabus
// ─────────────────────────────────────────────────────────────────

func BuildTaxonomy() []SubjectDef {
	return []SubjectDef{
		physicsSubject(),
		chemistrySubject(),
		mathematicsSubject(),
		biologySubject(),
	}
}

// ═══════════════════════════════════════════════════════════════
//  PHYSICS (BOTH — shared between JEE and NEET)
// ═══════════════════════════════════════════════════════════════

func physicsSubject() SubjectDef {
	return SubjectDef{
		Name: "Physics",
		Chapters: []ChapterDef{
			// ── Unit 1 ──
			{Name: "Units and Measurements", ExamTarget: "BOTH", Topics: []TopicDef{
				t("System of units and SI units"),
				t("Fundamental and derived units"),
				t("Least count and significant figures"),
				t("Errors in measurements"),
				t("Dimensions of physical quantities"),
				t("Dimensional analysis and applications"),
			}},
			// ── Unit 2 ──
			{Name: "Kinematics", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Frame of reference"),
				t("Motion in a straight line"),
				t("Speed and velocity"),
				t("Uniform and non-uniform motion"),
				t("Average speed and instantaneous velocity"),
				t("Uniformly accelerated motion"),
				t("Velocity-time and position-time graphs"),
				t("Relations for uniformly accelerated motion"),
				t("Relative velocity"),
				t("Scalars and vectors"),
				t("Vector addition and subtraction"),
				t("Resolution of a vector"),
				t("Motion in a plane"),
				t("Projectile motion"),
				t("Uniform circular motion"),
			}},
			// ── Unit 3 ──
			{Name: "Laws of Motion", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Force and inertia"),
				t("Newton's first law of motion"),
				t("Momentum"),
				t("Newton's second law of motion"),
				t("Impulse"),
				t("Newton's third law of motion"),
				t("Conservation of linear momentum"),
				t("Equilibrium of concurrent forces"),
				t("Static and kinetic friction"),
				t("Laws of friction and rolling friction"),
				t("Dynamics of uniform circular motion"),
				t("Centripetal force and applications"),
				t("Vehicle on level and banked road"),
			}},
			// ── Unit 4 ──
			{Name: "Work, Energy and Power", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Work done by constant and variable force"),
				t("Kinetic energy"),
				t("Potential energy"),
				t("Work-energy theorem"),
				t("Power"),
				t("Potential energy of a spring"),
				t("Conservation of mechanical energy"),
				t("Conservative and non-conservative forces"),
				t("Motion in a vertical circle"),
				t("Elastic and inelastic collisions in one and two dimensions"),
			}},
			// ── Unit 5 ──
			{Name: "Rotational Motion", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Centre of mass of two-particle system"),
				t("Centre of mass of a rigid body"),
				t("Moment of a force and torque"),
				t("Angular momentum"),
				t("Conservation of angular momentum"),
				t("Moment of inertia"),
				t("Radius of gyration"),
				t("Moments of inertia for simple geometrical objects"),
				t("Parallel and perpendicular axes theorems"),
				t("Equilibrium of rigid bodies"),
				t("Rigid body rotation and equations of rotational motion"),
				t("Comparison of linear and rotational motions"),
				tj("Rolling without slipping of rings, cylinders and spheres"),
				tj("Collision of point masses with rigid bodies"),
			}},
			// ── Unit 6 ──
			{Name: "Gravitation", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Universal law of gravitation"),
				t("Acceleration due to gravity"),
				t("Variation of g with altitude and depth"),
				t("Kepler's laws of planetary motion"),
				t("Gravitational potential energy"),
				t("Gravitational potential"),
				t("Escape velocity"),
				t("Motion of a satellite"),
				t("Orbital velocity, time period and energy of satellite"),
				tj("Geostationary orbits"),
			}},
			// ── Unit 7 ──
			{Name: "Properties of Solids and Liquids", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Elastic behaviour"),
				t("Stress-strain relationship"),
				t("Hooke's law"),
				t("Young's modulus, bulk modulus and modulus of rigidity"),
				t("Pressure due to a fluid column"),
				t("Pascal's law and applications"),
				t("Effect of gravity on fluid pressure"),
				t("Viscosity"),
				t("Stokes' law and terminal velocity"),
				t("Streamline and turbulent flow"),
				t("Critical velocity"),
				t("Bernoulli's principle and applications"),
				t("Surface energy and surface tension"),
				t("Angle of contact"),
				t("Excess pressure across a curved surface"),
				t("Drops, bubbles and capillary rise"),
				t("Heat and temperature"),
				t("Thermal expansion"),
				t("Specific heat capacity and calorimetry"),
				t("Change of state and latent heat"),
				t("Heat transfer: conduction, convection and radiation"),
				tj("Newton's law of cooling"),
				tj("Blackbody radiation: absorptive and emissive powers"),
				tj("Kirchhoff's law of radiation"),
				tj("Wien's displacement law"),
				tj("Stefan's law"),
			}},
			// ── Unit 8 ──
			{Name: "Thermodynamics", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Thermal equilibrium and zeroth law"),
				t("Concept of temperature"),
				t("Heat, work and internal energy"),
				t("First law of thermodynamics"),
				t("Isothermal process"),
				t("Adiabatic process"),
				t("Second law of thermodynamics"),
				t("Reversible and irreversible processes"),
				tj("Carnot engine and its efficiency"),
				tj("Equivalence of heat and work"),
			}},
			// ── Unit 9 ──
			{Name: "Kinetic Theory of Gases", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Equation of state of a perfect gas"),
				t("Work done on compressing a gas"),
				t("Kinetic theory: assumptions and concept of pressure"),
				t("Kinetic interpretation of temperature"),
				t("RMS speed of gas molecules"),
				t("Degrees of freedom"),
				t("Law of equipartition of energy"),
				t("Specific heat capacities of gases (Cv and Cp)"),
				t("Mean free path"),
				t("Avogadro's number"),
				tj("Average and most probable velocities"),
				tj("Law of partial pressures"),
				tj("Diffusion of gases"),
			}},
			// ── Unit 10 ──
			{Name: "Oscillations and Waves", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Periodic motion: time period and frequency"),
				t("Displacement as a function of time"),
				t("Simple harmonic motion (SHM) and its equation"),
				t("Phase in SHM"),
				t("Oscillations of a spring: restoring force and force constant"),
				t("Energy in SHM: kinetic and potential energies"),
				t("Simple pendulum and its time period"),
				t("Wave motion: longitudinal and transverse waves"),
				t("Speed of a travelling wave"),
				t("Displacement relation for a progressive wave"),
				t("Principle of superposition of waves"),
				t("Reflection of waves"),
				t("Standing waves in strings and organ pipes"),
				t("Fundamental mode and harmonics"),
				t("Beats"),
				tj("Forced and damped oscillations"),
				tj("Resonance in oscillations"),
				tj("Doppler effect in sound"),
				tj("Speed of sound in gases"),
			}},
			// ── Unit 11 ──
			{Name: "Electrostatics", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Electric charges and conservation of charge"),
				t("Coulomb's law"),
				t("Forces between multiple charges and superposition principle"),
				t("Continuous charge distribution"),
				t("Electric field due to a point charge"),
				t("Electric field lines"),
				t("Electric dipole and field due to a dipole"),
				t("Torque on a dipole in uniform electric field"),
				t("Electric flux"),
				t("Gauss's law and applications"),
				t("Field due to infinite long wire"),
				t("Field due to infinite plane sheet"),
				t("Field due to uniformly charged thin spherical shell"),
				t("Electric potential and its calculation"),
				t("Potential difference"),
				t("Equipotential surfaces"),
				t("Electrical potential energy of a system of charges"),
				t("Conductors and insulators"),
				t("Dielectrics and electric polarization"),
				t("Capacitance and parallel plate capacitor"),
				t("Combination of capacitors in series and parallel"),
				t("Energy stored in a capacitor"),
			}},
			// ── Unit 12 ──
			{Name: "Current Electricity", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Electric current"),
				t("Drift velocity and mobility"),
				t("Ohm's law"),
				t("Electrical resistance"),
				t("I-V characteristics of ohmic and non-ohmic conductors"),
				t("Electrical energy and power"),
				t("Electrical resistivity and conductivity"),
				t("Series and parallel combination of resistors"),
				t("Temperature dependence of resistance"),
				t("Internal resistance of a cell"),
				t("Potential difference and EMF of a cell"),
				t("Combination of cells in series and parallel"),
				t("Kirchhoff's laws and applications"),
				t("Wheatstone bridge"),
				t("Metre bridge"),
				tj("Potentiometer"),
				tj("Heating effect of current"),
			}},
			// ── Unit 13 ──
			{Name: "Magnetic Effects of Current and Magnetism", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Biot-Savart law"),
				t("Magnetic field due to current carrying circular loop"),
				t("Ampere's law and applications"),
				t("Magnetic field near a straight wire"),
				t("Magnetic field inside a solenoid"),
				t("Force on a moving charge in magnetic field"),
				t("Force on a current-carrying conductor in magnetic field"),
				t("Force between two parallel current-carrying conductors"),
				t("Definition of ampere"),
				t("Torque on a current loop in uniform magnetic field"),
				t("Moving coil galvanometer"),
				t("Conversion to ammeter and voltmeter"),
				t("Current loop as a magnetic dipole"),
				t("Bar magnet as equivalent solenoid"),
				t("Magnetic field lines"),
				t("Magnetic field due to a magnetic dipole"),
				t("Para-, dia- and ferromagnetic substances"),
				t("Effect of temperature on magnetic properties"),
				tj("Magnetic moment of a current loop"),
			}},
			// ── Unit 14 ──
			{Name: "Electromagnetic Induction and Alternating Currents", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Faraday's law of electromagnetic induction"),
				t("Induced EMF and current"),
				t("Lenz's law"),
				t("Eddy currents"),
				t("Self inductance"),
				t("Mutual inductance"),
				t("Alternating currents: peak and RMS value"),
				t("Reactance and impedance"),
				t("LCR series circuit"),
				t("Resonance in AC circuits"),
				t("Power in AC circuits"),
				t("Wattless current"),
				t("AC generator"),
				t("Transformer"),
				tj("RC, LR, LC and LCR circuits with DC and AC sources"),
			}},
			// ── Unit 15 ──
			{Name: "Electromagnetic Waves", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Displacement current"),
				t("Electromagnetic waves and their characteristics"),
				t("Transverse nature of electromagnetic waves"),
				t("Electromagnetic spectrum"),
				t("Radio waves, microwaves, infrared"),
				t("Visible, ultraviolet, X-rays, gamma rays"),
				t("Applications of electromagnetic waves"),
			}},
			// ── Unit 16 ──
			{Name: "Optics", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Reflection of light"),
				t("Spherical mirrors and mirror formula"),
				t("Refraction of light at plane and spherical surfaces"),
				t("Thin lens formula and lens maker formula"),
				t("Total internal reflection and its applications"),
				t("Magnification"),
				t("Power of a lens"),
				t("Combination of thin lenses in contact"),
				t("Refraction through a prism"),
				t("Microscope and astronomical telescope"),
				t("Wave optics: Huygens' principle"),
				t("Interference: Young's double-slit experiment"),
				t("Fringe width and coherent sources"),
				t("Diffraction due to a single slit"),
				t("Polarization of light"),
				t("Brewster's law"),
				t("Polaroids and uses of plane-polarized light"),
				tj("Deviation and dispersion of light by a prism"),
				tj("Combinations of mirrors and thin lenses"),
				tj("Rectilinear propagation of light"),
			}},
			// ── Unit 17 ──
			{Name: "Dual Nature of Matter and Radiation", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Dual nature of radiation"),
				t("Photoelectric effect"),
				t("Hertz and Lenard's observations"),
				t("Einstein's photoelectric equation"),
				t("Particle nature of light"),
				t("Matter waves and wave nature of particles"),
				t("de Broglie relation"),
				tj("Characteristic and continuous X-rays"),
				tj("Moseley's law"),
			}},
			// ── Unit 18 ──
			{Name: "Atoms and Nuclei", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Alpha-particle scattering experiment"),
				t("Rutherford's model of atom"),
				t("Bohr model of hydrogen atom"),
				t("Energy levels"),
				t("Hydrogen spectrum"),
				t("Composition and size of nucleus"),
				t("Atomic masses"),
				t("Mass-energy relation and mass defect"),
				t("Binding energy per nucleon and its variation"),
				t("Nuclear fission"),
				t("Nuclear fusion"),
				t("Radioactive decay"),
				t("Decay constant, half-life and mean life"),
				t("Alpha, beta and gamma radiations"),
			}},
			// ── Unit 19 ──
			{Name: "Electronic Devices", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Semiconductors"),
				t("Semiconductor diode: I-V characteristics"),
				t("Forward and reverse bias"),
				t("Diode as a rectifier"),
				t("LED characteristics"),
				t("Photodiode"),
				t("Solar cell"),
				t("Zener diode"),
				t("Zener diode as a voltage regulator"),
				t("Logic gates: OR, AND, NOT, NAND, NOR"),
			}},
			// ── Unit 20 ──
			{Name: "Experimental Skills", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Vernier calipers"),
				t("Screw gauge"),
				t("Simple pendulum experiment"),
				t("Metre scale and principle of moments"),
				t("Young's modulus experiment"),
				t("Surface tension by capillary rise"),
				t("Coefficient of viscosity (terminal velocity)"),
				t("Speed of sound using resonance tube"),
				t("Specific heat capacity of solid and liquid"),
				t("Resistivity using metre bridge"),
				t("Ohm's law verification"),
				t("Galvanometer: half deflection method"),
				t("Focal length of mirrors and lenses"),
				t("Angle of deviation vs angle of incidence (prism)"),
				t("Refractive index of glass slab"),
				t("p-n junction diode characteristics"),
				t("Zener diode characteristics and breakdown voltage"),
			}},
		},
	}
}

// ═══════════════════════════════════════════════════════════════
//  CHEMISTRY (BOTH for core chapters, JEE for Advanced-only)
// ═══════════════════════════════════════════════════════════════

func chemistrySubject() SubjectDef {
	return SubjectDef{
		Name: "Chemistry",
		Chapters: []ChapterDef{
			// ─── PHYSICAL CHEMISTRY ───

			{Name: "Some Basic Concepts in Chemistry", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Matter and its nature"),
				t("Dalton's atomic theory"),
				t("Concept of atom, molecule, element and compound"),
				t("Laws of chemical combination"),
				t("Atomic and molecular masses"),
				t("Mole concept"),
				t("Molar mass"),
				t("Percentage composition"),
				t("Empirical and molecular formulae"),
				t("Chemical equations and stoichiometry"),
				t("Oxidation-reduction reactions"),
				t("Concentration: mole fraction, molarity, molality, normality"),
			}},
			{Name: "Atomic Structure", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Nature of electromagnetic radiation"),
				t("Photoelectric effect"),
				t("Spectrum of hydrogen atom"),
				t("Bohr model of hydrogen atom"),
				t("Limitations of Bohr's model"),
				t("Dual nature of matter"),
				t("de Broglie's relationship"),
				t("Heisenberg uncertainty principle"),
				t("Quantum mechanical model of atom"),
				t("Concept of atomic orbitals"),
				t("Quantum numbers and their significance"),
				t("Shapes of s, p and d orbitals"),
				t("Electron spin and spin quantum number"),
				t("Aufbau principle"),
				t("Pauli's exclusion principle"),
				t("Hund's rule"),
				t("Electronic configuration of elements"),
			}},
			{Name: "Chemical Bonding and Molecular Structure", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Kossel-Lewis approach to chemical bond formation"),
				t("Ionic bonding and lattice enthalpy"),
				t("Factors affecting formation of ionic bonds"),
				t("Covalent bonding"),
				t("Electronegativity"),
				t("Fajan's rule"),
				t("Dipole moment"),
				t("VSEPR theory and shapes of molecules"),
				t("Hybridisation involving s, p and d orbitals"),
				t("Resonance"),
				t("Valence bond theory"),
				t("Molecular orbital theory"),
				t("Types of molecular orbitals: bonding and antibonding"),
				t("Sigma and pi bonds"),
				t("Molecular orbital electronic configurations"),
				t("Bond order, bond length and bond energy"),
				t("Metallic bonding"),
				t("Hydrogen bonding and its applications"),
				t("Polarity in molecules"),
			}},
			{Name: "Chemical Thermodynamics", ExamTarget: "BOTH", Topics: []TopicDef{
				t("System and surroundings"),
				t("Extensive and intensive properties"),
				t("State functions"),
				t("Types of processes"),
				t("First law of thermodynamics"),
				t("Concept of work, heat and internal energy"),
				t("Enthalpy"),
				t("Heat capacity and molar heat capacity"),
				t("Hess's law of constant heat summation"),
				t("Enthalpies of bond dissociation, combustion, formation"),
				t("Enthalpies of atomization, sublimation, phase transition"),
				t("Enthalpy of hydration, ionization and solution"),
				t("Second law of thermodynamics"),
				t("Entropy"),
				t("Gibbs energy"),
				t("Criteria of equilibrium and spontaneity"),
				t("Standard Gibbs energy change and equilibrium constant"),
			}},
			{Name: "Solutions", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Methods of expressing concentration"),
				t("Molality, molarity, mole fraction, percentage"),
				t("Vapour pressure of solutions"),
				t("Raoult's law"),
				t("Ideal and non-ideal solutions"),
				t("Vapour pressure-composition plots"),
				t("Colligative properties"),
				t("Relative lowering of vapour pressure"),
				t("Depression of freezing point"),
				t("Elevation of boiling point"),
				t("Osmotic pressure"),
				t("Determination of molecular mass"),
				t("Abnormal molar mass and van't Hoff factor"),
				tj("Henry's law"),
			}},
			{Name: "Equilibrium", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Concept of dynamic equilibrium"),
				t("Equilibria involving physical processes"),
				t("Law of chemical equilibrium"),
				t("Equilibrium constants Kp and Kc"),
				t("Significance of delta-G in chemical equilibrium"),
				t("Factors affecting equilibrium"),
				t("Le Chatelier's principle"),
				t("Weak and strong electrolytes"),
				t("Ionization of electrolytes"),
				t("Acids and bases: Arrhenius, Bronsted-Lowry and Lewis concepts"),
				t("Ionization of water and pH scale"),
				t("Common ion effect"),
				t("Hydrolysis of salts"),
				t("Solubility product and its applications"),
				t("Buffer solutions"),
				tj("Reaction quotient"),
			}},
			{Name: "Redox Reactions and Electrochemistry", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Electronic concepts of oxidation and reduction"),
				t("Redox reactions"),
				t("Oxidation number and rules for assigning"),
				t("Balancing of redox reactions"),
				t("Electrolytic and metallic conduction"),
				t("Conductance in electrolytic solutions"),
				t("Molar conductivity and variation with concentration"),
				t("Kohlrausch's law and applications"),
				t("Electrochemical cells: electrolytic and galvanic"),
				t("Electrode potentials and standard electrode potential"),
				t("Half-cell and cell reactions"),
				t("EMF of a galvanic cell"),
				t("Nernst equation and applications"),
				t("Relationship between cell potential and Gibbs energy"),
				t("Dry cell and lead accumulator"),
				t("Fuel cells"),
				tj("Faraday's laws of electrolysis"),
				tj("Electrochemical series"),
				tj("Corrosion"),
			}},
			{Name: "Chemical Kinetics", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Rate of a chemical reaction"),
				t("Factors affecting rate: concentration, temperature, pressure, catalyst"),
				t("Elementary and complex reactions"),
				t("Order and molecularity of reactions"),
				t("Rate law and rate constant"),
				t("Differential and integral forms of zero and first order reactions"),
				t("Characteristics and half-lives of reactions"),
				t("Effect of temperature on rate"),
				t("Arrhenius equation and activation energy"),
				t("Collision theory of bimolecular gaseous reactions"),
				tj("Catalysis: homogeneous and heterogeneous"),
				tj("Activity and selectivity of solid catalysts"),
				tj("Enzyme catalysis and mechanism"),
			}},

			// ─── JEE Advanced-only Physical Chemistry ───

			{Name: "States of Matter: Gases and Liquids", ExamTarget: "JEE", Topics: []TopicDef{
				t("Gas laws and ideal gas equation"),
				t("Absolute scale of temperature"),
				t("Deviation from ideality and van der Waals equation"),
				t("Average, RMS and most probable velocities"),
				t("Law of partial pressures"),
				t("Diffusion of gases"),
				t("Intermolecular interactions"),
				t("Vapour pressure of liquids"),
				t("Surface tension of liquids"),
				t("Viscosity of liquids"),
			}},
			{Name: "Solid State", ExamTarget: "JEE", Topics: []TopicDef{
				t("Classification of solids"),
				t("Crystalline state"),
				t("Seven crystal systems"),
				t("Close packed structures: cubic and hexagonal"),
				t("Packing in fcc, bcc and hcp lattices"),
				t("Nearest neighbours"),
				t("Ionic radii and radius ratio"),
				t("Point defects"),
			}},
			{Name: "Surface Chemistry", ExamTarget: "JEE", Topics: []TopicDef{
				t("Adsorption: physisorption and chemisorption"),
				t("Freundlich adsorption isotherm"),
				t("Colloids: types, preparation and properties"),
				t("Emulsions, surfactants and micelles"),
			}},

			// ─── INORGANIC CHEMISTRY ───

			{Name: "Classification of Elements and Periodicity in Properties", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Modern periodic law and periodic table"),
				t("s, p, d and f block elements"),
				t("Periodic trends in atomic and ionic radii"),
				t("Ionization enthalpy"),
				t("Electron gain enthalpy"),
				t("Valence and oxidation states"),
				t("Electronegativity"),
				t("Chemical reactivity trends"),
			}},
			{Name: "Hydrogen", ExamTarget: "JEE", Topics: []TopicDef{
				t("Position of hydrogen in periodic table"),
				t("Isotopes of hydrogen"),
				t("Preparation, properties and uses of hydrogen"),
				t("Hydrides: ionic, covalent and interstitial"),
				t("Properties of water and heavy water"),
				t("Hydrogen peroxide: preparation, reactions and structure"),
				t("Hydrogen as a fuel"),
			}},
			{Name: "s-Block Elements", ExamTarget: "JEE", Topics: []TopicDef{
				t("Alkali and alkaline earth metals"),
				t("Reactivity towards air, water, dihydrogen, halogens"),
				t("Reducing nature and solutions in liquid ammonia"),
				t("Oxides, hydroxides, halides and salts of oxoacids"),
				t("Anomalous behaviour of lithium and beryllium"),
				t("Compounds of sodium: carbonate, chloride, hydroxide, bicarbonate"),
				t("Compounds of calcium: oxide, hydroxide, carbonate, sulphate"),
			}},
			{Name: "p-Block Elements", ExamTarget: "BOTH", Topics: []TopicDef{
				t("General introduction: Groups 13 to 18"),
				t("Electronic configuration and trends in properties"),
				t("Unique behaviour of first element in each group"),
				t("Group 13: boron, aluminium compounds and uses"),
				t("Group 14: carbon allotropes, silicon compounds"),
				t("Group 15: nitrogen, phosphorus compounds"),
				t("Group 16: oxygen, sulphur and their compounds"),
				t("Group 17: halogens and their compounds"),
				t("Group 18: noble gases, xenon compounds"),
				tj("Borax, orthoboric acid, diborane, boron trifluoride"),
				tj("Aluminium chloride and alums"),
				tj("Carbon monoxide and carbon dioxide"),
				tj("Silicon dioxide, silicones, silicates, zeolites"),
				tj("Dinitrogen, ammonia, nitric acid"),
				tj("Phosphine, PCl3, PCl5"),
				tj("Oxides of nitrogen, oxoacids of phosphorus"),
				tj("Dioxygen, ozone, sulphur dioxide, sulfuric acid"),
				tj("Oxoacids of sulphur"),
				tj("Chlorine, HCl, interhalogen compounds"),
				tj("Oxoacids of halogens, bleaching powder"),
			}},
			{Name: "d-Block and f-Block Elements", ExamTarget: "BOTH", Topics: []TopicDef{
				t("General introduction to transition elements"),
				t("Electronic configuration of transition elements"),
				t("General trends in properties of first row transition elements"),
				t("Ionization enthalpy of d-block"),
				t("Oxidation states"),
				t("Atomic radii"),
				t("Colour and catalytic behaviour"),
				t("Magnetic properties"),
				t("Complex formation"),
				t("Interstitial compounds"),
				t("Alloy formation"),
				t("Preparation and properties of K2Cr2O7 and KMnO4"),
				t("Lanthanoids: electronic configuration and contraction"),
				t("Actinoids: electronic configuration and oxidation states"),
				tj("Standard electrode potentials of d-block"),
				tj("Oxoanions of chromium and manganese"),
			}},
			{Name: "Coordination Compounds", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Werner's theory"),
				t("Ligands and coordination number"),
				t("Denticity and chelation"),
				t("IUPAC nomenclature of coordination compounds"),
				t("Isomerism in coordination compounds"),
				t("Valence bond approach to bonding"),
				t("Crystal field theory"),
				t("Colour and magnetic properties of coordination compounds"),
				t("Importance of coordination compounds"),
				tj("Cis-trans and ionization isomerism"),
				tj("Hybridization and geometries"),
				tj("Spectrochemical series"),
				tj("Stability of coordination compounds"),
				tj("Metal carbonyls"),
			}},
			{Name: "Isolation of Metals", ExamTarget: "JEE", Topics: []TopicDef{
				t("Metal ores and their concentration"),
				t("Thermodynamic principles of metallurgy"),
				t("Electrochemical principles of metallurgy"),
				t("Extraction of iron, copper, zinc"),
				t("Extraction of aluminium"),
				t("Cyanide process for silver and gold"),
				t("Refining of metals"),
			}},
			{Name: "Principles of Qualitative Analysis", ExamTarget: "JEE", Topics: []TopicDef{
				t("Qualitative analysis: Groups I to V"),
				t("Identification of cations"),
				t("Identification of anions"),
			}},
			{Name: "Environmental Chemistry", ExamTarget: "JEE", Topics: []TopicDef{
				t("Atmospheric pollution"),
				t("Water pollution"),
				t("Soil pollution"),
				t("Industrial waste"),
				t("Strategies to control environmental pollution"),
				t("Green chemistry"),
			}},

			// ─── ORGANIC CHEMISTRY ───

			{Name: "Purification and Characterisation of Organic Compounds", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Crystallization"),
				t("Sublimation"),
				t("Distillation"),
				t("Differential extraction"),
				t("Chromatography: principles and applications"),
				t("Detection of nitrogen, sulphur, phosphorus and halogens"),
				t("Quantitative analysis: estimation of C, H, N, halogens, S, P"),
				t("Empirical and molecular formulae of organic compounds"),
			}},
			{Name: "Some Basic Principles of Organic Chemistry", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Tetravalency of carbon"),
				t("Hybridisation: sp3, sp2, sp"),
				t("Classification based on functional groups"),
				t("Homologous series"),
				t("Structural isomerism"),
				t("Stereoisomerism"),
				t("IUPAC nomenclature"),
				t("Covalent bond fission: homolytic and heterolytic"),
				t("Free radicals, carbocations and carbanions"),
				t("Electrophiles and nucleophiles"),
				t("Inductive effect"),
				t("Electromeric effect"),
				t("Resonance and hyperconjugation"),
				t("Substitution, addition, elimination and rearrangement reactions"),
				tj("Enantiomers and diastereomers"),
				tj("Meso compounds"),
				tj("Determination of empirical and molecular formulae by combustion"),
				tj("Aromaticity"),
				tj("Stability of carbocations, carbanions and free radicals"),
				tj("Acidity and basicity of organic compounds"),
			}},
			{Name: "Hydrocarbons", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Classification and isomerism of hydrocarbons"),
				t("Alkanes: conformations (Sawhorse and Newman)"),
				t("Mechanism of halogenation of alkanes"),
				t("Alkenes: geometrical isomerism"),
				t("Electrophilic addition of alkenes"),
				t("Addition of H2, halogens, water, hydrogen halides to alkenes"),
				t("Markownikoff's rule and peroxide effect"),
				t("Ozonolysis"),
				t("Polymerization of alkenes"),
				t("Alkynes: acidic character"),
				t("Addition reactions of alkynes"),
				t("Aromatic hydrocarbons: benzene structure and aromaticity"),
				t("Mechanism of electrophilic substitution in benzene"),
				t("Halogenation and nitration of benzene"),
				t("Friedel-Crafts alkylation and acylation"),
				t("Directive influence of functional group in monosubstituted benzene"),
				tj("Allylic and benzylic halogenation"),
				tj("Cyclic polymerization of alkynes"),
			}},
			{Name: "Organic Compounds Containing Halogens", ExamTarget: "BOTH", Topics: []TopicDef{
				t("General methods of preparation of haloalkanes"),
				t("Properties and reactions of haloalkanes"),
				t("Nature of C-X bond"),
				t("Mechanisms of substitution reactions: SN1 and SN2"),
				t("Uses and environmental effects of chloroform, iodoform"),
				t("Freons and DDT"),
				tj("Rearrangement reactions of alkyl carbocations"),
				tj("Grignard reactions"),
				tj("Nucleophilic substitution: stereochemical aspects"),
				tj("Haloarenes: Fittig and Wurtz-Fittig reactions"),
				tj("Nucleophilic aromatic substitution in haloarenes"),
			}},
			{Name: "Organic Compounds Containing Oxygen", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Alcohols: identification of primary, secondary and tertiary"),
				t("Mechanism of dehydration of alcohols"),
				t("Phenols: acidic nature"),
				t("Electrophilic substitution of phenols"),
				t("Reimer-Tiemann reaction"),
				t("Ethers: structure"),
				t("Aldehyde and ketones: nature of carbonyl group"),
				t("Nucleophilic addition to carbonyl group"),
				t("Relative reactivity of aldehydes and ketones"),
				t("Nucleophilic addition reactions: HCN, NH3 derivatives"),
				t("Grignard reagent with carbonyl compounds"),
				t("Oxidation and reduction of carbonyl compounds"),
				t("Wolf-Kishner and Clemmensen reduction"),
				t("Aldol condensation"),
				t("Cannizzaro reaction"),
				t("Haloform reaction"),
				t("Carboxylic acids: acidic strength and factors"),
				tj("Kolbe reaction of phenols"),
				tj("Aspirin synthesis"),
				tj("Williamson's synthesis of ethers"),
				tj("C-O bond cleavage in ethers"),
				tj("Esterification of alcohols"),
				tj("Reactions of alcohols with Na, phosphorus halides, ZnCl2/HCl, SOCl2"),
				tj("Preparation of carboxylic acids from nitriles and Grignard reagents"),
				tj("Reduction and halogenation of carboxylic acids"),
				tj("Formation of esters, acid chlorides and amides"),
			}},
			{Name: "Organic Compounds Containing Nitrogen", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Amines: nomenclature and classification"),
				t("Structure and basic character of amines"),
				t("Identification of primary, secondary and tertiary amines"),
				t("Diazonium salts and importance in synthesis"),
				tj("Preparation of amines from nitro compounds, nitriles and amides"),
				tj("Hoffmann bromamide degradation"),
				tj("Gabriel phthalimide synthesis"),
				tj("Reaction of amines with nitrous acid"),
				tj("Azo coupling reaction"),
				tj("Sandmeyer and related reactions"),
				tj("Carbylamine reaction"),
				tj("Hinsberg test"),
				tj("Alkylation and acylation of amines"),
			}},
			{Name: "Biomolecules", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Classification of carbohydrates"),
				t("Monosaccharides: glucose and fructose"),
				t("Oligosaccharides: sucrose, lactose and maltose"),
				t("Amino acids and peptide bond"),
				t("Polypeptides and proteins"),
				t("Protein structure: primary, secondary, tertiary and quaternary"),
				t("Denaturation of proteins"),
				t("Enzymes"),
				t("Vitamins: classification and functions"),
				t("Nucleic acids: DNA and RNA structure"),
				t("Biological functions of nucleic acids"),
				t("Hormones: general introduction"),
				tj("Anomers of carbohydrates"),
				tj("Glycoside formation and hydrolysis of disaccharides"),
				tj("Fibrous and globular proteins"),
			}},
			{Name: "Polymers", ExamTarget: "JEE", Topics: []TopicDef{
				t("Types of polymerization: addition and condensation"),
				t("Homo and copolymers"),
				t("Natural rubber"),
				t("Cellulose"),
				t("Nylon"),
				t("Teflon and Bakelite"),
				t("PVC"),
				t("Biodegradable polymers"),
				t("Applications of polymers"),
			}},
			{Name: "Chemistry in Everyday Life", ExamTarget: "JEE", Topics: []TopicDef{
				t("Drug-target interaction"),
				t("Antacids and antihistamines"),
				t("Tranquilizers and analgesics"),
				t("Antimicrobials and antifertility drugs"),
				t("Artificial sweeteners"),
				t("Soaps and detergents: cleansing action"),
			}},
			{Name: "Practical Chemistry", ExamTarget: "BOTH", Topics: []TopicDef{
				t("Detection of extra elements in organic compounds"),
				t("Detection of functional groups: hydroxyl, carbonyl, carboxyl, amino"),
				t("Preparation of inorganic compounds: Mohr's salt, potash alum"),
				t("Preparation of organic compounds: acetanilide, aniline yellow, iodoform"),
				t("Titrimetric exercises: acids, bases, indicators"),
				t("Qualitative salt analysis: cations and anions"),
				t("Enthalpy of solution and neutralization"),
				t("Preparation of lyophilic and lyophobic sols"),
				t("Kinetic study of iodide-hydrogen peroxide reaction"),
			}},
		},
	}
}

// ═══════════════════════════════════════════════════════════════
//  MATHEMATICS (JEE only — not part of NEET)
// ═══════════════════════════════════════════════════════════════

func mathematicsSubject() SubjectDef {
	return SubjectDef{
		Name: "Mathematics",
		Chapters: []ChapterDef{
			{Name: "Sets, Relations and Functions", ExamTarget: "JEE", Topics: []TopicDef{
				t("Sets and their representation"),
				t("Union, intersection and complement of sets"),
				t("Algebraic properties of sets"),
				t("Power set"),
				t("De Morgan's laws"),
				t("Relations and types of relations"),
				t("Equivalence relations"),
				t("Functions: one-one, into, onto"),
				t("Composition of functions"),
				t("Invertible functions"),
				t("Even and odd functions"),
				t("Domain, codomain and range"),
				tj("Special functions: polynomial, exponential, logarithmic, absolute value, greatest integer"),
				tj("Symmetric difference of sets"),
			}},
			{Name: "Complex Numbers and Quadratic Equations", ExamTarget: "JEE", Topics: []TopicDef{
				t("Complex numbers as ordered pairs of reals"),
				t("Representation in form a + ib"),
				t("Argand diagram"),
				t("Algebra of complex numbers"),
				t("Modulus and argument of complex number"),
				t("Quadratic equations in real and complex systems"),
				t("Relations between roots and coefficients"),
				t("Nature of roots"),
				t("Formation of quadratic equations with given roots"),
				tj("Polar representation of complex numbers"),
				tj("Triangle inequality"),
				tj("Cube roots of unity"),
				tj("Geometric interpretations of complex numbers"),
			}},
			{Name: "Matrices and Determinants", ExamTarget: "JEE", Topics: []TopicDef{
				t("Matrices and algebra of matrices"),
				t("Types of matrices"),
				t("Determinants of order two and three"),
				t("Evaluation of determinants"),
				t("Area of triangles using determinants"),
				t("Adjoint and inverse of a square matrix"),
				t("Test of consistency"),
				t("Solution of simultaneous linear equations using matrices"),
				tj("Elementary row and column transformations"),
				tj("Diagonal, symmetric and skew-symmetric matrices"),
				tj("Transpose of a matrix"),
			}},
			{Name: "Permutations and Combinations", ExamTarget: "JEE", Topics: []TopicDef{
				t("Fundamental principle of counting"),
				t("Permutations"),
				t("Combinations"),
				t("Meaning of P(n,r) and C(n,r)"),
				t("Simple applications of permutations and combinations"),
			}},
			{Name: "Binomial Theorem", ExamTarget: "JEE", Topics: []TopicDef{
				t("Binomial theorem for positive integral index"),
				t("General term and middle term"),
				t("Simple applications of binomial theorem"),
				tj("Properties of binomial coefficients"),
			}},
			{Name: "Sequence and Series", ExamTarget: "JEE", Topics: []TopicDef{
				t("Arithmetic progressions"),
				t("Geometric progressions"),
				t("Insertion of arithmetic and geometric means"),
				t("Relation between AM and GM"),
				t("Sum of finite arithmetic and geometric progressions"),
				tj("Infinite geometric series"),
				tj("Sum of first n natural numbers, squares and cubes"),
				tj("Logarithms and their properties"),
			}},
			{Name: "Limit, Continuity and Differentiability", ExamTarget: "JEE", Topics: []TopicDef{
				t("Real-valued functions and algebra of functions"),
				t("Polynomial, rational, trigonometric functions"),
				t("Logarithmic and exponential functions"),
				t("Inverse functions"),
				t("Graphs of simple functions"),
				t("Limits of functions"),
				t("Continuity of a function"),
				t("Differentiability"),
				t("Differentiation of sum, difference, product and quotient"),
				t("Differentiation of trigonometric functions"),
				t("Differentiation of inverse trigonometric functions"),
				t("Differentiation of logarithmic and exponential functions"),
				t("Differentiation of composite and implicit functions"),
				t("Derivatives of order up to two"),
				t("Rate of change of quantities"),
				t("Monotonic increasing and decreasing functions"),
				t("Maxima and minima of functions of one variable"),
				tj("L'Hospital's rule"),
				tj("Continuity of composite functions"),
				tj("Intermediate value property"),
				tj("Tangents and normals"),
				tj("Rolle's theorem"),
				tj("Lagrange's mean value theorem"),
				tj("Geometric interpretation of derivatives"),
			}},
			{Name: "Integral Calculus", ExamTarget: "JEE", Topics: []TopicDef{
				t("Integral as an anti-derivative"),
				t("Fundamental integrals: algebraic, trigonometric, exponential, logarithmic"),
				t("Integration by substitution"),
				t("Integration by parts"),
				t("Integration by partial fractions"),
				t("Integration using trigonometric identities"),
				t("Fundamental theorem of calculus"),
				t("Properties of definite integrals"),
				t("Evaluation of definite integrals"),
				t("Areas bounded by simple curves"),
				tj("Definite integrals as limit of sums"),
			}},
			{Name: "Differential Equations", ExamTarget: "JEE", Topics: []TopicDef{
				t("Ordinary differential equations: order and degree"),
				t("Solution by separation of variables"),
				t("Solution of homogeneous differential equations"),
				t("Linear differential equation of type dy/dx + Py = Q"),
				tj("Formation of ordinary differential equations"),
			}},
			{Name: "Coordinate Geometry", ExamTarget: "JEE", Topics: []TopicDef{
				t("Cartesian system of rectangular coordinates"),
				t("Distance formula"),
				t("Section formula"),
				t("Locus and its equation"),
				t("Slope of a line"),
				t("Parallel and perpendicular lines"),
				t("Intercepts on coordinate axes"),
				t("Various forms of equation of a straight line"),
				t("Intersection of lines"),
				t("Angles between two lines"),
				t("Conditions for concurrence of three lines"),
				t("Distance of a point from a line"),
				t("Centroid, orthocentre and circumcentre of a triangle"),
				t("Equation of a circle in various forms"),
				t("Radius and centre of a circle"),
				t("Points of intersection of a line and a circle"),
				t("Conic sections: parabola"),
				t("Conic sections: ellipse"),
				t("Conic sections: hyperbola"),
				t("Equations of conic sections in standard forms"),
				tj("Equation of tangent and normal to conics"),
				tj("Parametric equations of conics"),
				tj("Foci, directrices and eccentricity"),
				tj("Equation of the bisector of angle between two lines"),
				tj("Locus problems"),
				tj("Incentre of a triangle"),
			}},
			{Name: "Three Dimensional Geometry", ExamTarget: "JEE", Topics: []TopicDef{
				t("Coordinates of a point in space"),
				t("Distance between two points"),
				t("Section formula"),
				t("Direction ratios and direction cosines"),
				t("Angle between two intersecting lines"),
				t("Equation of a line in space"),
				t("Skew lines"),
				t("Shortest distance between two lines"),
				tj("Equation of a plane"),
				tj("Distance of a point from a plane"),
				tj("Angle between two planes"),
				tj("Angle between a line and a plane"),
				tj("Coplanar lines"),
			}},
			{Name: "Vector Algebra", ExamTarget: "JEE", Topics: []TopicDef{
				t("Vectors and scalars"),
				t("Addition of vectors"),
				t("Components of a vector in 2D and 3D"),
				t("Scalar product (dot product)"),
				t("Vector product (cross product)"),
				tj("Scalar triple product"),
				tj("Vector triple product"),
				tj("Geometrical interpretations of vector products"),
			}},
			{Name: "Statistics and Probability", ExamTarget: "JEE", Topics: []TopicDef{
				t("Measures of dispersion"),
				t("Mean, median, mode of grouped and ungrouped data"),
				t("Standard deviation and variance"),
				t("Mean deviation"),
				t("Probability of an event"),
				t("Addition and multiplication theorems of probability"),
				t("Bayes' theorem"),
				t("Probability distribution of a random variable"),
				tj("Conditional probability"),
				tj("Independence of events"),
				tj("Mean and variance of a random variable"),
				tj("Computation of probability using permutations and combinations"),
				tj("Analysis of frequency distributions with same mean but different variance"),
			}},
			{Name: "Trigonometry", ExamTarget: "JEE", Topics: []TopicDef{
				t("Trigonometric identities"),
				t("Trigonometric functions"),
				t("Inverse trigonometric functions and their properties"),
				tj("Periodicity and graphs of trigonometric functions"),
				tj("Addition and subtraction formulae"),
				tj("Multiple and sub-multiple angle formulae"),
				tj("General solution of trigonometric equations"),
			}},
		},
	}
}

// ═══════════════════════════════════════════════════════════════
//  BIOLOGY (NEET only — not part of JEE)
// ═══════════════════════════════════════════════════════════════

func biologySubject() SubjectDef {
	return SubjectDef{
		Name: "Biology",
		Chapters: []ChapterDef{
			{Name: "Diversity in Living World", ExamTarget: "NEET", Topics: []TopicDef{
				t("What is living"),
				t("Biodiversity and need for classification"),
				t("Three domains of life"),
				t("Taxonomy and systematics"),
				t("Concept of species and taxonomical hierarchy"),
				t("Binomial nomenclature"),
				t("Tools for study of taxonomy"),
				t("Five kingdom classification"),
				t("Salient features and classification of Monera"),
				t("Salient features and classification of Protista"),
				t("Salient features and classification of Fungi"),
				t("Kingdom Plantae"),
				t("Kingdom Animalia"),
				t("Viruses, viroids, prions and lichens"),
				t("Morphology and modification of root, stem, leaf"),
				t("Morphology of flower, fruit and seed"),
				t("Description of families: Fabaceae, Solanaceae, Liliaceae"),
				t("Classification of animal kingdom: basis and features"),
			}},
			{Name: "Structural Organisation in Animals and Plants", ExamTarget: "NEET", Topics: []TopicDef{
				t("Tissues in plants: meristematic and permanent"),
				t("Anatomy of dicot and monocot root"),
				t("Anatomy of dicot and monocot stem"),
				t("Anatomy of leaf"),
				t("Secondary growth in plants"),
				t("Animal tissues: epithelial, connective, muscular, neural"),
				t("Morphology and anatomy of earthworm"),
				t("Morphology and anatomy of cockroach"),
				t("Morphology and anatomy of frog"),
			}},
			{Name: "Cell Structure and Function", ExamTarget: "NEET", Topics: []TopicDef{
				t("Cell theory and cell as basic unit of life"),
				t("Prokaryotic and eukaryotic cell structure"),
				t("Plant cell and animal cell"),
				t("Cell envelope and cell membrane"),
				t("Cell wall"),
				t("Endomembrane system: ER, Golgi, lysosomes, vacuoles"),
				t("Mitochondria"),
				t("Plastids"),
				t("Ribosomes"),
				t("Cytoskeleton, cilia, flagella and centrosome"),
				t("Nucleus and chromosomes"),
				t("Chemical composition of living cells"),
				t("Biomolecules: carbohydrates, proteins, lipids, nucleic acids"),
				t("Enzymes: types, properties, enzyme action"),
				t("Cell cycle"),
				t("Mitosis"),
				t("Meiosis"),
			}},
			{Name: "Plant Physiology", ExamTarget: "NEET", Topics: []TopicDef{
				t("Transport of water and minerals in plants"),
				t("Imbibition, osmosis, plasmolysis"),
				t("Water potential"),
				t("Long distance transport of water"),
				t("Transpiration: opening and closing of stomata"),
				t("Uptake and translocation of mineral nutrients"),
				t("Transport of food: phloem transport and mass flow"),
				t("Mineral nutrition: essential elements"),
				t("Macro and micronutrients and their role"),
				t("Deficiency symptoms"),
				t("Mineral toxicity"),
				t("Nitrogen metabolism and nitrogen cycle"),
				t("Nitrogen fixation"),
				t("Photosynthesis as means of autotrophic nutrition"),
				t("Site of photosynthesis"),
				t("Photochemical and biosynthetic phases"),
				t("Cyclic and non-cyclic photophosphorylation"),
				t("Chemiosmotic hypothesis"),
				t("C3 and C4 pathways"),
				t("Photorespiration"),
				t("Factors affecting photosynthesis"),
				t("Respiration: glycolysis, fermentation, aerobic respiration"),
				t("TCA cycle and electron transport system"),
				t("Energy relations"),
				t("Amphibolic pathways"),
				t("Respiratory quotient"),
				t("Plant growth and development"),
				t("Phases and rates of plant growth"),
				t("Conditions of growth"),
				t("Differentiation, dedifferentiation and redifferentiation"),
				t("Seed germination and dormancy"),
				t("Plant growth regulators: auxin, gibberellin, cytokinin, ethylene, ABA"),
				t("Vernalisation and photoperiodism"),
			}},
			{Name: "Human Physiology", ExamTarget: "NEET", Topics: []TopicDef{
				t("Digestion and absorption"),
				t("Alimentary canal and digestive glands"),
				t("Role of digestive enzymes and gastrointestinal hormones"),
				t("Peristalsis, digestion, absorption and assimilation"),
				t("Caloric value of proteins, carbohydrates and fats"),
				t("Nutritional and digestive disorders"),
				t("Breathing and exchange of gases"),
				t("Respiratory organs in animals"),
				t("Respiratory system in humans"),
				t("Mechanism of breathing"),
				t("Exchange of gases"),
				t("Transport of gases and regulation of respiration"),
				t("Respiratory volumes and disorders"),
				t("Body fluids and circulation"),
				t("Composition of blood and lymph"),
				t("Blood groups"),
				t("Coagulation of blood"),
				t("Human circulatory system: structure of heart"),
				t("Cardiac cycle, cardiac output, ECG"),
				t("Double circulation"),
				t("Regulation of cardiac activity"),
				t("Disorders of circulatory system"),
				t("Excretory products and their elimination"),
				t("Excretory organs"),
				t("Human excretory system: structure and function of kidney"),
				t("Urine formation"),
				t("Osmoregulation"),
				t("Regulation of kidney function"),
				t("Role of other organs in excretion"),
				t("Disorders of excretory system"),
				t("Locomotion and movement"),
				t("Types of movement"),
				t("Skeletal muscle structure and contraction"),
				t("Skeletal system and its functions"),
				t("Joints and disorders of muscular and skeletal system"),
				t("Neural control and coordination"),
				t("Neuron and nerves"),
				t("Nervous system in humans: CNS and PNS"),
				t("Generation and conduction of nerve impulse"),
				t("Reflex action and reflex arc"),
				t("Sensory perception: sense organs"),
				t("Chemical coordination and integration"),
				t("Endocrine glands and hormones"),
				t("Human endocrine system"),
				t("Hormones of heart, kidney and gastrointestinal tract"),
				t("Mechanism of hormone action"),
				t("Role of hormones as messengers and regulators"),
				t("Hypo- and hyperactivity and related disorders"),
			}},
			{Name: "Reproduction", ExamTarget: "NEET", Topics: []TopicDef{
				t("Asexual reproduction"),
				t("Sexual reproduction in flowering plants"),
				t("Flower structure"),
				t("Development of male and female gametophytes"),
				t("Pollination: types, agencies and examples"),
				t("Outbreeding devices"),
				t("Pollen-pistil interaction"),
				t("Double fertilisation"),
				t("Post-fertilisation: endosperm and embryo development"),
				t("Development of seed and formation of fruit"),
				t("Apomixis, parthenocarpy, polyembryony"),
				t("Human reproduction: male and female reproductive systems"),
				t("Microscopic anatomy of testis and ovary"),
				t("Gametogenesis: spermatogenesis and oogenesis"),
				t("Menstrual cycle"),
				t("Fertilisation and embryo development up to blastocyst"),
				t("Implantation"),
				t("Pregnancy and placenta formation"),
				t("Parturition and lactation"),
				t("Reproductive health"),
				t("Sexually transmitted diseases"),
				t("Birth control methods and contraception"),
				t("Medical termination of pregnancy"),
				t("Amniocentesis"),
				t("Infertility and assisted reproductive technologies: IVF, ZIFT, GIFT"),
			}},
			{Name: "Genetics and Evolution", ExamTarget: "NEET", Topics: []TopicDef{
				t("Mendelian inheritance"),
				t("Incomplete dominance and co-dominance"),
				t("Multiple alleles and inheritance of blood groups"),
				t("Pleiotropy"),
				t("Polygenic inheritance"),
				t("Chromosome theory of inheritance"),
				t("Chromosomes and genes"),
				t("Sex determination in humans, birds and honey bee"),
				t("Linkage and crossing over"),
				t("Sex-linked inheritance: haemophilia, colour blindness"),
				t("Mendelian disorders: thalassemia"),
				t("Chromosomal disorders: Down's, Turner's, Klinefelter's syndrome"),
				t("Search for genetic material"),
				t("DNA as genetic material"),
				t("Structure of DNA and RNA"),
				t("DNA packaging"),
				t("DNA replication"),
				t("Central dogma"),
				t("Transcription"),
				t("Genetic code"),
				t("Translation and protein biosynthesis"),
				t("Gene expression and regulation: Lac operon"),
				t("Genome and human genome project"),
				t("DNA fingerprinting"),
				t("Origin of life"),
				t("Biological evolution and evidences"),
				t("Darwin's contribution"),
				t("Modern synthetic theory of evolution"),
				t("Mechanism of evolution: mutation and recombination"),
				t("Natural selection: types and examples"),
				t("Gene flow and genetic drift"),
				t("Hardy-Weinberg's principle"),
				t("Adaptive radiation"),
				t("Human evolution"),
			}},
			{Name: "Biology and Human Welfare", ExamTarget: "NEET", Topics: []TopicDef{
				t("Health and disease"),
				t("Pathogens and parasites causing human diseases"),
				t("Malaria and filariasis"),
				t("Ascariasis"),
				t("Typhoid, pneumonia and common cold"),
				t("Amoebiasis and ringworm"),
				t("Dengue and chikungunya"),
				t("Basic concepts of immunology"),
				t("Vaccines"),
				t("Cancer"),
				t("HIV and AIDS"),
				t("Adolescence, drug and alcohol abuse"),
				t("Tobacco abuse"),
				t("Microbes in household food processing"),
				t("Microbes in industrial production"),
				t("Microbes in sewage treatment"),
				t("Microbes in energy generation"),
				t("Biocontrol agents and biofertilizers"),
			}},
			{Name: "Biotechnology and Its Applications", ExamTarget: "NEET", Topics: []TopicDef{
				t("Principles of biotechnology"),
				t("Recombinant DNA technology"),
				t("Process of genetic engineering"),
				t("Application in health: human insulin and vaccine production"),
				t("Gene therapy"),
				t("Genetically modified organisms: Bt crops"),
				t("Transgenic animals"),
				t("Biosafety issues: biopiracy and patents"),
			}},
			{Name: "Ecology and Environment", ExamTarget: "NEET", Topics: []TopicDef{
				t("Organisms and environment"),
				t("Population interactions: mutualism, competition, predation, parasitism"),
				t("Population attributes: growth, birth rate, death rate"),
				t("Age distribution"),
				t("Ecosystem: patterns and components"),
				t("Productivity and decomposition"),
				t("Energy flow in ecosystem"),
				t("Pyramids of number, biomass and energy"),
				t("Concept of biodiversity"),
				t("Patterns of biodiversity"),
				t("Importance of biodiversity"),
				t("Loss of biodiversity"),
				t("Biodiversity conservation"),
				t("Hotspots and endangered organisms"),
				t("Extinction and Red Data Book"),
				t("Biosphere reserves, national parks and sanctuaries"),
				t("Sacred groves"),
			}},
		},
	}
}
